### ISSUE TITLE
个人设置页面，已经绑定过的微信，在其它账号注册的时候试图再次绑定，没有正确提醒

### ISSUE THREAD

**Issue by IHCI-HG** [IHCI-HG/IHCI-RE#13]
个人设置页面，已经绑定过的微信，在其它账号注册的时候试图再次绑定同一微信号，没有正确提醒

系统不允许一个微信号绑定多个账号，之前的版本是有提醒该微信已经绑定的，现在会的提醒toast是已经请完善资料，而不是微信号已经绑定。

**Comment by Egolas** [comment]
是不是新账号没有完善资料，因为我是写在处理路由的时候就判断是否完成资料填写。
如果是的话，要不要改成只有完成了资料填写，才可以绑定与关注

**Comment by IHCI-HG** [comment]
是还没完善资料，这是在完善资料过程中，绑定微信应该优先先判断一下微信绑定逻辑
