### ISSUE TITLE
个人设置页 头像上传

### ISSUE THREAD

**Issue by Egolas** [IHCI-HG/IHCI-RE#14]
头像上传，选择了PNG格式图片，仍显示上传格式错误
![2](https://user-images.githubusercontent.com/17876505/42439849-95c483d2-8396-11e8-8d8f-f997a109950f.PNG)
![3](https://user-images.githubusercontent.com/17876505/42439853-989562d4-8396-11e8-91f8-e3d6ba57906b.PNG)

**Comment by ying971101** [comment]
之前的文件名后缀要求必须是小写，已在filemodel分支上更正该bug
