### ISSUE TITLE
Topic 页面 创建回复

### ISSUE THREAD

**Issue by Egolas** [IHCI-HG/IHCI-RE#8]
1、Topic页面创建回复有时候已输入内容，没有报错，并离开了输入子组件，但是页面中对应出现的新回复项无内容
2、Topic页面创建回复有时候会显示参数不全，即使已输入内容。但是再次点击回复，可以正常创建回复

疑似原因在于setState函数的延迟生效

**Comment by OoKyleoO** [comment]
已解决，暂未合并
