### ISSUE TITLE
Topic页面 回复样式问题

### ISSUE THREAD

**Issue by Egolas** [IHCI-HG/IHCI-RE#9]
标题2样式错误
![default](https://user-images.githubusercontent.com/17876505/42429259-9e0e0a6c-836a-11e8-854b-563f6a491c21.PNG)

**Comment by OoKyleoO** [comment]
收到

**Comment by OoKyleoO** [comment]
这是编辑器插件本身问题……

**Comment by OoKyleoO** [comment]
好像cnpm install了之后好了 或者是因为pull了一下master的代码
